kind: Service
apiVersion: v1
metadata:
  name: minecraft-manager
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: api
  selector:
    app: minecraft-manager
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: minecraft
  labels:
    app: minecraft-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-manager
  template:
    metadata:
      labels:
        app: minecraft-manager
    spec:
      containers:
      - image: vikpande/minecraft-manager
        name: minecraft-manager
        ports:
        - containerPort: 3000